title: "@akaoio/battle"
description: "Universal terminal application testing framework with real PTY emulation and screenshots"
name: "@akaoio/battle"
usage: |
  import { Battle } from "@akaoio/battle"
  
  const battle = new Battle({
    command: 'npm',
    args: ['install'],
    timeout: 30000
  })
  
  await battle.spawn()
  await battle.expect('packages installed')
  battle.cleanup()
features:
  - "Real PTY Emulation - Uses actual pseudo-terminals, not fake pipes"
  - "StarCraft-Style Replay - Record and playback with microsecond precision" 
  - "Self-Testing Framework - Tests itself recursively for reliability"
  - "Cross-Platform Support - Linux, macOS, Windows with native PTY"
  - "Visual Debugging - HTML replay export with YouTube-style controls"
  - "Zero Mock Policy - 100% real implementation, no mocks or stubs"
